Repository PyWavelets/pywt, pull requests merged in 2018-08, with the labels that each got.

#398 MAINT: update .gitignore for files generated during build.
  .gitignore
Labels: maintenance

#399 BLD: allow `pip install PyWavelets` to work in an empty venv.
  setup.py
Labels: build, maintenance

#403 Change ValueError to UserWarning when level is > dwt_max_level
  doc/release/1.0.0-notes.rst
  pywt/_multilevel.py
  pywt/tests/test_multilevel.py
Labels: bug

#404 BLD: fix ReadTheDocs build. Outdated NumPy gave a conflict with MPL.
  util/readthedocs/requirements.txt
Labels: maintenance

#341 new utilities for reshaping and predetermining the shapes of n-d DWT coefficients
  doc/source/ref/dwt-coefficient-handling.rst
  doc/source/ref/dwt-discrete-wavelet-transform.rst
  pywt/_multilevel.py
  pywt/tests/test_multilevel.py
Labels: enhancement

#204 fully separable wavelet transform
  demo/fswt.py
  demo/fswt_mondrian.py
  doc/source/conf.py
  doc/source/ref/nd-dwt-and-idwt.rst
  pywt/_multilevel.py
  pywt/tests/test_multilevel.py
  pywt/tests/test_swt.py
Labels: enhancement

#301 WIP DOC: add high-level overview of multi-level decompositions
  doc/source/pyplots/plot_2d_bases.py
  doc/source/pyplots/plot_mallat_2d.py
  doc/source/ref/2d-decompositions-overview.rst
  doc/source/ref/index.rst
  doc/source/ref/nd-dwt-and-idwt.rst
Labels: documentation

#406 update v1.0.0 release notes
  doc/release/1.0.0-notes.rst
Labels: documentation

#411 minor edit to documentation front page
  doc/source/index.rst
Labels: documentation

#412 DOC: update 1.0 release notes
  doc/release/1.0.0-notes.rst
Labels: documentation

#413 add wavelets.pybytes.com disclaimer
  doc/source/ref/wavelets.rst
  doc/source/regression/wavelet.rst
Labels: documentation

#414 update PR and issues lists in release notes
  doc/release/1.0.0-notes.rst
Labels: documentation

#415 BLD: add missing import of textwrap
  setup.py
Labels: bug

#416 TST: relax tolerance in test_wavelet_packet_dtypes
  pywt/tests/test_wp.py
  pywt/tests/test_wp2d.py
Labels: maintenance

#419 add Appveyor, TravisCI, RTD and Zenodo badges to the README
  README.rst
Labels: documentation
