Repository PyWavelets/pywt, pull requests merged in 2018-07, with the labels that each got.

#354 add firm (semi-soft) and non-negative garotte thresholding
  doc/source/common_refs.rst
  doc/source/conf.py
  doc/source/index.rst
  doc/source/pyplots/plot_thresholds.py
  doc/source/ref/thresholding-functions.rst
  pywt/_thresholding.py
  pywt/tests/test_thresholding.py
Labels: enhancement

#382 avoid FutureWarnings related to multiindexing in Numpy1.15
  pywt/_multilevel.py
  pywt/_swt.py
  pywt/tests/test_multidim.py
  pywt/tests/test_multilevel.py
  pywt/tests/test_swt.py
Labels: maintenance

#383 adding Community guidelines
  CONTRIBUTING.rst
  community_guidelines.rst
  doc/source/common_refs.rst
  doc/source/index.rst
Labels: documentation

#351 Add two new antisymmetric edge modes
  doc/source/pyplots/plot_boundary_modes.py
  doc/source/ref/signal-extension-modes.rst
  pywt/_extensions/_pywt.pyx
  pywt/_extensions/c/common.h
  pywt/_extensions/c/convolution.template.c
  pywt/_extensions/common.pxd
  pywt/tests/data/dwt_matlabR2012a_result.npz
  pywt/tests/data/generate_matlab_data.py
  pywt/tests/test_matlab_compatibility.py
  pywt/tests/test_modes.py
Labels: enhancement

#387 improve CWT docs
  doc/source/pyplots/cwt_scaling_demo.py
  doc/source/ref/cwt.rst
  doc/source/ref/wavelets.rst
  pywt/_extensions/_pywt.pyx
Labels: documentation

#384 swap swt2 coefficient order (and remove FutureWarnings)
  doc/release/1.0.0-notes.rst
  pywt/_swt.py
  pywt/tests/test_swt.py
Labels: API change

#390 MAINT: update Python version support. Closes gh-385.
  .travis.yml
  doc/release/1.0.0-notes.rst
  setup.py
Labels: maintenance

#392 do not force float64 dtype on assignment to Node, Node2D
  doc/release/1.0.0-notes.rst
  pywt/_wavelet_packets.py
  pywt/tests/test_wp.py
  pywt/tests/test_wp2d.py
Labels: bug

#381 Fix corner case for small scales in CWT
  pywt/_cwt.py
  pywt/tests/test_cwt_wavelets.py
Labels: bug
