Repository PyWavelets/pywt, pull requests merged in 2018-02, with the labels that each got.

#344 force legacy numpy repr for doctests
  doc/source/conf.py
  pywt/__init__.py
  pywt/_utils.py
  util/refguide_check.py
Labels: documentation, maintenance

#349 test case for CWT with complex input
  demo/cwt_analysis.py
  pywt/tests/test_cwt_wavelets.py
Labels: testing

#353 DOC: add citation info to the front page of the docs.
  doc/source/index.rst
Labels: documentation

#350 better document the size requirements for swt/swt2/swtn
  pywt/_extensions/_swt.pyx
  pywt/_swt.py
  pywt/tests/test_swt.py
Labels: documentation
