Repository PyWavelets/pywt, pull requests merged in 2019-07, with the labels that each got.

#499 register markers for pytest 4.5 compatibility
  MANIFEST.in
  pywt/conftest.py
Labels: testing

#506 Guard against trying to transform along size 0 axes
  pywt/_extensions/_dwt.pyx
  pywt/_extensions/_swt.pyx
  pywt/tests/test_dwt_idwt.py
  pywt/tests/test_swt.py
Labels: bug

#471 user-friendly error messages about multilevel DWT format
  pywt/_multilevel.py
  pywt/tests/test_multilevel.py
Labels: documentation, maintenance

#490 cwt with fft convolution support
  .travis.yml
  README.rst
  benchmarks/benchmarks/cwt_benchmarks.py
  doc/source/common_refs.rst
  doc/source/install.rst
  pywt/_cwt.py
  pywt/tests/test_cwt_wavelets.py
Labels: enhancement

#507 preserve single precision in CWT
  benchmarks/benchmarks/cwt_benchmarks.py
  pywt/_cwt.py
  pywt/tests/test_cwt_wavelets.py
Labels: enhancement

#476 swt normalization and option to trim the approximation coefficients
  pywt/_dwt.py
  pywt/_extensions/_swt.pyx
  pywt/_multidim.py
  pywt/_multilevel.py
  pywt/_swt.py
  pywt/tests/test_swt.py
Labels: enhancement
