Repository PyWavelets/pywt, pull requests merged in 2019-10, with the labels that each got.

#478 update the pad utility function and make it part of the public API
  doc/source/conf.py
  doc/source/pyplots/plot_boundary_modes.py
  doc/source/ref/signal-extension-modes.rst
  pywt/_doc_utils.py
  pywt/_dwt.py
  pywt/_utils.py
  pywt/tests/test_dwt_idwt.py
Labels: enhancement

#439 fix the phase of CWT when using complex mother wavelets
  doc/release/1.1.0-notes.rst
  pywt/_cwt.py
  pywt/tests/data/generate_matlab_data_cwt.py
  pywt/tests/test_matlab_compatibility_cwt.py
  util/authors.py
Labels: maintenance

#521 DOC: adopt the SciPy Code of Conduct
  community_guidelines.rst
  doc/source/common_refs.rst
  doc/source/contributing.rst
  doc/source/dev/conduct/code_of_conduct.rst
  doc/source/dev/conduct/report_handling_manual.rst
  doc/source/dev/index.rst
Labels: documentation

#523 DOC: update release notes for v1.1
  doc/release/1.1.0-notes.rst
Labels: documentation

#526 remove unmerged PR from list [ci skip]
  doc/release/1.1.0-notes.rst
Labels: documentation

#530 Release 1.1.1
  appveyor.yml
  doc/release/1.1.1-notes.rst
  doc/source/release.1.1.1.rst
  doc/source/releasenotes.rst
  setup.py
Labels: maintenance
