Repository PyWavelets/pywt, pull requests merged in 2021-11, with the labels that each got.

#605 CI: rename job steps from "scikit-image" to "PyWavelets"
  .github/workflows/tests.yml
Labels: maintenance

#603 Run tests on Python 3.10
  .github/workflows/tests.yml
  appveyor.yml
Labels: maintenance

#606 MAINT: fix doc build on ReadTheDocs
  doc/source/conf.py
  util/readthedocs/requirements.txt
Labels: maintenance

#546 ENH: make Wavelet, WaveletPacket, WaveletPacket2D and ContinuousWavelet pickleable
  pywt/_extensions/_pywt.pyx
  pywt/_wavelet_packets.py
  pywt/tests/test_cwt_wavelets.py
  pywt/tests/test_wavelet.py
  pywt/tests/test_wp.py
  pywt/tests/test_wp2d.py
Labels: enhancement

#609 MAINT: fix `origin='image'` calls that Matplotlib no longer supports
  demo/swt2.py
  demo/wp_2d.py
Labels: maintenance

#527 Multiresolution Analysis
  demo/mra2d.py
  demo/mra_vs_swt.py
  doc/source/ref/index.rst
  doc/source/ref/mra.rst
  pywt/__init__.py
  pywt/_cwt.py
  pywt/_dwt.py
  pywt/_mra.py
  pywt/_multidim.py
  pywt/_multilevel.py
  pywt/_swt.py
  pywt/tests/test_mra.py
  pywt/tests/test_swt.py
Labels: enhancement

#608 BLD: update Cython build dependency to recent release and <3.0
  pyproject.toml
Labels: maintenance

#604 MAINT: update pyproject.toml and setup.py for Python 3.10
  pyproject.toml
  setup.py
Labels: maintenance

#610 Update GitHub Actions workflow to build Python 3.10 wheels
  .github/workflows/wheel_tests_and_release.yml
Labels: maintenance

#611 MAINT: fix doc build issues
  doc/source/ref/mra.rst
  doc/source/ref/wavelet-packets.rst
  pywt/_mra.py
Labels: maintenance, documentation

#393 Wavelet packets: extend to nD and support subsets of the axes
  demo/wp_nd.py
  doc/source/ref/wavelet-packets.rst
  pywt/_multidim.py
  pywt/_wavelet_packets.py
  pywt/tests/test_wp.py
  pywt/tests/test_wp2d.py
  pywt/tests/test_wpnd.py
Labels: enhancement

#612 Release notes for v1.2.0
  .mailmap
  doc/release/1.2.0-notes.rst
  util/authors.py
  util/gh_lists.py
Labels: maintenance, documentation

#613 Fix bugs in automated wheel deployment
  .github/workflows/wheel_tests_and_release.yml
Labels: maintenance

#614 DOC: Update the developer docs on how to make a release
  doc/source/dev/how_to_release.rst
Labels: documentation
