Repository PyWavelets/pywt, pull requests merged in 2022-09, with the labels that each got.

#648 Run GitHub actions test cases using Python 3.11
  .github/workflows/tests.yml
Labels: maintenance

#647 provide setuptools upper bound for robustness against future changes
  pyproject.toml
Labels: maintenance, build

#641 test_cwt_batch can have small differences on some arches (resolves #640)
  pywt/tests/test_cwt_wavelets.py
Labels: maintenance

#649 Update wheel building workflow to include Python 3.11
  .github/workflows/wheel_tests_and_release.yml
  pyproject.toml
Labels: maintenance, build

#650 Upgrade GitHub Actions
  .github/workflows/tests.yml
  .github/workflows/wheel_tests_and_release.yml
Labels: maintenance

#635 added a frequency2scale function as the dual to scale2frequency
  doc/source/ref/cwt.rst
  pywt/_functions.py
  pywt/tests/test_functions.py
Labels: enhancement

#653 allow `git blame` to ignore specific revisions (e.g. codespell changes)
  .git-blame-ignore-revs
Labels: maintenance

#652 add release notes for v1.4.0
  doc/release/1.4.0-notes.rst
  doc/source/releasenotes.rst
Labels: documentation

#654 Remove `string_types`, which is a remnant of Python 2 support
  pywt/_dwt.py
  pywt/_utils.py
Labels: maintenance

#657 release v1.4.1, updating classifiers and python_requires in setup.py
  .github/workflows/tests.yml
  appveyor.yml
  doc/release/1.4.1-notes.rst
  doc/source/release.1.4.1.rst
  doc/source/releasenotes.rst
  pyproject.toml
  setup.py
Labels: maintenance
