Repository PyWavelets/pywt, pull requests merged in 2024-03, with the labels that each got.

#704 DOC: Migrate to `pydata-sphinx-theme`
  .github/workflows/tests.yml
  doc/release/0.5.0-notes.rst
  doc/source/_static/github.png
  doc/source/_static/twitter.png
  doc/source/_templates/editdocument.html
  doc/source/_templates/page.html
  doc/source/_templates/quicklinks.html
  doc/source/conf.py
  doc/source/dev/testing.rst
  doc/source/index.rst
  doc/source/install.rst
  doc/source/ref/signal-extension-modes.rst
  util/readthedocs/requirements.txt
Labels: documentation

#678 Additional documentation for cwt (issue #676)
  doc/source/pyplots/cwt_wavelet_frequency_bandwidth_demo.py
  doc/source/pyplots/plot_cwt_scaleogram.py
  doc/source/pyplots/plot_wavelets.py
  doc/source/ref/cwt.rst
  doc/source/ref/wavelets.rst
Labels: documentation

#709 mymindstorm/setup-emscripten --> mymindstorm/setup-emsdk
  .github/workflows/emscripten.yml
Labels: testing

#710 Upload nightly wheels for PyWavelets to the Scientific Python Nightly Wheels index on Anaconda
  .github/workflows/emscripten.yml
Labels: CI

#711 CI: tweaks to CI job triggers and names
  .github/workflows/emscripten.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
Labels: CI

#708 Keep GitHub Actions up to date with GitHub's Dependabot
  .github/dependabot.yml
Labels: CI

#716 TST/CI: mark some tests as slow and avoid running them in wheel builds and Emscripten job
  .github/workflows/emscripten.yml
  .github/workflows/wheel_tests_and_release.yml
  pywt/tests/test_mra.py
  pywt/tests/test_perfect_reconstruction.py
Labels: testing

#714 Upload dev wheels to Anaconda.org + revamp wheels publishing workflow
  .github/workflows/wheel_tests_and_release.yml
Labels: CI

#720 BLD: avoid warnings from including deprecated NumPy API
  pywt/_extensions/meson.build
Labels: build

#719 CI: Build `musllinux` aarch64 and x86_64 wheels, and native macOS arm64 wheels
  .github/workflows/wheel_tests_and_release.yml
Labels: build, CI

#684 Rename master branch to main
  .github/workflows/emscripten.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .github/workflows/wheel_tests_and_release.yml
  CONTRIBUTING.rst
  README.rst
  benchmarks/asv.conf.json
  doc/source/common_refs.rst
  doc/source/conf.py
  doc/source/dev/testing.rst
  doc/source/ref/2d-decompositions-overview.rst
Labels: maintenance

#723 MAINT: use `numpy-config` and fix support for numpy 2.0
  pywt/_cwt.py
  pywt/_dwt.py
  pywt/_extensions/meson.build
  pywt/_multidim.py
  pywt/_multilevel.py
  pywt/_swt.py
  pywt/_utils.py
  pywt/tests/test_mra.py
Labels: maintenance

#724 DOC/REL: prepare 1.6.0 release, set version to 1.6.0rc1
  doc/release/1.6.0-notes.rst
  doc/source/release.1.6.0.rst
  doc/source/releasenotes.rst
  meson.build
  pyproject.toml
  util/version_utils.py
Labels: maintenance, documentation

#726 MAINT: set version to 1.7.0.dev0
  meson.build
  pyproject.toml
  util/version_utils.py
Labels: maintenance

#722 Drop support for older dependencies (see SPEC 0)
  .github/workflows/tests.yml
  .github/workflows/wheel_tests_and_release.yml
  README.rst
  appveyor.yml
  doc/source/dev/testing.rst
  pyproject.toml
  pywt/_cwt.py
  tox.ini
Labels: maintenance

#728 Initial steps towards interactive documentation via JupyterLite
  .gitignore
  doc/source/_static/pywavelets.css
  doc/source/conf.py
  doc/source/ref/cwt.rst
  doc/source/ref/other-functions.rst
  doc/source/ref/signal-extension-modes.rst
  doc/source/ref/wavelets.rst
  doc/source/try_examples.json
  pywt/_cwt.py
  pywt/data/_wavelab_signals.py
  util/readthedocs/requirements.txt
Labels: documentation
