Repository PyWavelets/pywt, pull requests merged in 2024-06, with the labels that each got.

#747 Use `scipy-doctest` instead of `refguide-check`
  .github/workflows/tests.yml
  pywt/_cwt.py
  pywt/_extensions/_pywt.pyx
  pywt/_multilevel.py
  pywt/data/_readers.py
  pywt/data/_wavelab_signals.py
  util/refguide_check.py
Labels: maintenance, documentation

#744 CI, BLD: Use `cibuildwheel` to build and test Pyodide/WASM wheels for PyWavelets
  .github/workflows/emscripten.yml
Labels: maintenance, CI

#754 DOC: Fix failing documentation build
  .github/workflows/tests.yml
Labels: maintenance

#753 CI: Add CI to test on free-threaded Python
  .github/workflows/tests.yml
  pywt/_extensions/_swt.pyx
  pywt/_extensions/meson.build
Labels: CI

#756 CI: Add CI to release nightly wheels against free-threaded Python 3.13
  .github/workflows/freethreaded_wheels.yml
  meson.build
Labels: CI

#757 CI: add macOS nightly wheels for free-threaded CPython
  .github/workflows/freethreaded_wheels.yml
  .github/workflows/wheel_tests_and_release.yml
Labels: enhancement, CI
