Repository PyWavelets/pywt, pull requests merged in 2025-08, with the labels that each got.

#802 `cwt`: log `scales` in docstring example
  pywt/_cwt.py
Labels: documentation

#570 ENH: allow user to set `precision` in CWT, increase default to 12
  pywt/_cwt.py
  pywt/tests/test_matlab_compatibility_cwt.py
Labels: enhancement

#815 CI: test Python 3.14 and 3.14t in regular CI jobs
  .github/workflows/tests.yml
Labels: CI

#819 CI: Add support for building pywt wheels for windows arm64
  .github/workflows/wheel_tests_and_release.yml
Labels: CI
